site_name: Curiosity Guidelines
site_url: https://curiosity-guidelines.readthedocs.io
site_description: База знаний/PlayBook Curiosity
site_author: SIIS Ltd
copyright: <a href="https://siisltd.ru">SIIS Ltd</a> © 2021

nav:
  - 'Введение': 'index.md'
  - 'Общие правила': 
    - 'Общие моменты': 'development/index.md'
    - 'История изменений': 'development/changelog.md'
    - 'Версионирование': 'development/versioning.md'
    - 'Конфигурирование приложений': 'development/configurations.md'
    - 'Документация': 'development/docs.md'
    - 'Настройка CI/CD': 'development/cicd.md'
    - 'nginx': 'development/nginx.md'
    - 'systemd': 'development/systemd.md'
    - 'Тестирование': 'development/testing.md'
  - 'git':
      - 'Commits': 'git/commits.md'
      - 'Ветки': 'git/branches.md'
      - 'Merge Requests': 'git/merge_requests.md'
  - '.NET':
      - 'Conventions': 'dotNetCodeStyle/conventions.md'
      - 'Комментарии': 'dotNetCodeStyle/comments.md'
      - 'Исключения': 'dotNetCodeStyle/exceptions.md'
      - 'Локализация': 'dotNetCodeStyle/localization.md'
      - 'SOLID': 'dotNetCodeStyle/solid.md'
      - 'Структура репозитория': 'dotNetCodeStyle/solutions.md'
      - 'Асинхронное программирование': 'dotNetCodeStyle/async.md'
      - 'Работы с коллекциями': 'dotNetCodeStyle/collections.md'
      - 'EntityFramework': 'dotNetCodeStyle/ef.md'
      - 'Dapper': 'dotNetCodeStyle/dapper.md'
      - 'Логирование': 'dotNetCodeStyle/logs.md'
      - 'Performance': 'dotNetCodeStyle/performance.md'
  - 'WEB':
      - 'Intro': 'web/index.md'
      - 'Оптимизации': 'web/optimisations.md'
      - 'API':
        - 'Intro': 'web/api/index.md'
        - 'Ответы (Response)': 'web/api/response.md'
        - 'Валидация': 'web/api/validation.md'
        - 'Исключения': 'web/api/exceptions.md'
        - 'Авторизация': 'web/api/authorization.md'
        - 'Документация': 'web/api/documentation.md'
  - 'Базы данных':
      - 'Intro': 'database/index.md'
      - 'PostgresSQL': 'database/postgres.md'
      - 'Оптимизации': 'database/optimisations.md'
  - 'Образование': 'education.md'
  - 'FAQ': 'faq.md'

theme:
  name: material
  language: ru
  favicon: images/siisltd.png
  logo: images/dark_siisltd.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: red
    accent: red
  features:
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs

extra_css:
  - 'stylesheets/extra.css'

plugins:
  - search:
      lang: 
        - ru
        - en
