-- Миграция, которая создаёт необходимые для identity сущности
CREATE TABLE "AspNetRoles"
(
	"Id" bigint generated by default as identity
		CONSTRAINT "PK_AspNetRoles"
			PRIMARY KEY,
	"Name" varchar(256) NOT NULL,
	"NormalizedName" varchar(256) NOT NULL,
	"ConcurrencyStamp" text
);

ALTER TABLE "AspNetRoles" owner TO %USER%;

CREATE UNIQUE INDEX "RoleNameIndex"	ON "AspNetRoles" ("NormalizedName");

CREATE TABLE "AspNetUsers"
(
	"Id" bigint generated by default as identity
		CONSTRAINT "PK_AspNetUsers" PRIMARY KEY,
	"Created" timestamp DEFAULT timezone('UTC'::text, NOW()) NOT NULL,
	"IsDeleted" boolean DEFAULT FALSE NOT NULL,
	"Sex" int4 NOT NULL,
    "Email" varchar(256),
    "NormalizedEmail" varchar(256),
	"UserName" varchar(256) NOT NULL,
	"NormalizedUserName" varchar(256) NOT NULL,
    "TimeZoneId" varchar(100) NOT NULL,
	"EmailConfirmed" boolean NOT NULL,
	"PasswordHash" text,
	"SecurityStamp" text,
	"ConcurrencyStamp" text,
	"PhoneNumber" text,
	"PhoneNumberConfirmed" boolean NOT NULL,
	"TwoFactorEnabled" boolean NOT NULL,
	"LockoutEnd" timestamp with time zone,
	"LockoutEnabled" boolean NOT NULL,
	"AccessFailedCount" integer NOT NULL
);

ALTER TABLE "AspNetUsers" owner TO %USER%;

CREATE UNIQUE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE TABLE "AspNetRoleClaims"
(
	"Id" integer generated by default as identity
		CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY,
	"RoleId" bigint NOT NULL
		CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"	REFERENCES "AspNetRoles" ON DELETE CASCADE,
	"ClaimType" text,
	"ClaimValue" text
);

ALTER TABLE "AspNetRoleClaims" owner TO %USER%;

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE TABLE "AspNetUserClaims"
(
	"Id" integer generated by default as identity
		CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY,
	"UserId" bigint NOT NULL
		CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"	REFERENCES "AspNetUsers" ON DELETE CASCADE,
	"ClaimType" text,
	"ClaimValue" text
);

ALTER TABLE "AspNetUserClaims" owner TO %USER%;

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE TABLE "AspNetUserLogins"
(
	"LoginProvider" text NOT NULL,
	"ProviderKey" text NOT NULL,
	"ProviderDisplayName" text,
	"UserId" bigint NOT NULL
		CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
			REFERENCES "AspNetUsers"
				ON DELETE CASCADE,
	CONSTRAINT "PK_AspNetUserLogins"
		PRIMARY KEY ("LoginProvider", "ProviderKey")
);

ALTER TABLE "AspNetUserLogins" owner TO %USER%;

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE TABLE "AspNetUserRoles"
(
	"UserId" bigint NOT NULL
		CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" REFERENCES "AspNetUsers" ON DELETE CASCADE,
	"RoleId" bigint NOT NULL
		CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" REFERENCES "AspNetRoles"	ON DELETE CASCADE,
	CONSTRAINT "PK_AspNetUserRoles"
		PRIMARY KEY ("UserId", "RoleId")
);

ALTER TABLE "AspNetUserRoles" owner TO %USER%;

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE TABLE "AspNetUserTokens"
(
	"UserId" bigint NOT NULL
		CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"	REFERENCES "AspNetUsers" ON DELETE CASCADE,
	"LoginProvider" text NOT NULL,
	"Name" text NOT NULL,
	"Value" text,
	CONSTRAINT "PK_AspNetUserTokens"
		PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

ALTER TABLE "AspNetUserTokens" owner TO %USER%;
